export const Constant = {
    INCREMENT: 'INCREMENT',
    DECREMENT:'DECREMENT',
    LOGIN:'LOGIN',
    CREATEACCOUNT:'CREATEACCOUNT',
    SUCCESS:'SUCCESS',
    CREATENOTE:'CREATENOTE',
    GETNOTES:'GETNOTES',
    EDITNOTES:'EDITNOTES',
    RESET_EDITDATA:'RESET_EDITDATA,'
};